
terms <- c(
  'term',
  'recr',
  'rslt',
  'type',
  'cond',
  'intr',
  'titles',
  'outc',
  'spons',
  'lead',
  'id',
  'state1',
  'cntry1',
  'state2',
  'cntry2',
  'state3',
  'cntry3',
  'locn',
  'gndr',
  'age',
  'phase',
  'fund',
  'safe',
  'rcv_s',
  'rcv_e',
  'lup_s',
  'lup_e'
  )

labels <- c("Search Terms",
"Recruitment",
"Study Results",
"Study Type",
"Conditions",
"Interventions",
"Study Titles",
"Outcome Measures",
"Sponsor/Collaborators",
"Sponsor (Lead)",
"Study IDs",
"State 1",
"Country 1",
"State 2",
"Country 2",
"State 3",
"Country 3",
"Location Terms",
"Gender",
"Age Group",
"Phase",
"Funder Type",
"Safety Issue",
"First Received - Start",
"First Received - End",
"Last Updated - Start",
"Last Updated - End"
)

helpurl <- c(
'http://clinicaltrials.gov/ct2/help/search_terms',
'http://clinicaltrials.gov/ct2/help/recruitment',
'http://clinicaltrials.gov/ct2/help/study_results',
'http://clinicaltrials.gov/ct2/help/study_type',
'http://clinicaltrials.gov/ct2/help/conditions_instr',
'http://clinicaltrials.gov/ct2/help/interventions_instr',
'http://clinicaltrials.gov/ct2/help/titles',
'http://clinicaltrials.gov/ct2/help/outcome_measures',
'http://clinicaltrials.gov/ct2/help/sponsorandcollaborators',
'http://clinicaltrials.gov/ct2/help/sponsor',
'http://clinicaltrials.gov/ct2/help/study_ids',
'http://clinicaltrials.gov/ct2/help/country_state',
'http://clinicaltrials.gov/ct2/help/country_state',
'http://clinicaltrials.gov/ct2/help/country_state',
'http://clinicaltrials.gov/ct2/help/country_state',
'http://clinicaltrials.gov/ct2/help/country_state',
'http://clinicaltrials.gov/ct2/help/country_state',
'http://clinicaltrials.gov/ct2/help/location_terms',
'http://clinicaltrials.gov/ct2/help/gender',
'http://clinicaltrials.gov/ct2/help/age_group',
'http://clinicaltrials.gov/ct2/help/phase_instr',
'http://clinicaltrials.gov/ct2/help/funded_by',
'http://clinicaltrials.gov/ct2/help/safety_issue',
'http://clinicaltrials.gov/ct2/help/first_received',
'http://clinicaltrials.gov/ct2/help/first_received',
'http://clinicaltrials.gov/ct2/help/last_updated',
'http://clinicaltrials.gov/ct2/help/last_updated')

advanced_search_terms <- data.frame(keys = terms, description = labels, help = helpurl, stringsAsFactors = FALSE)
rownames(advanced_search_terms) <- advanced_search_terms$keys
#write.csv(advanced_search_terms, "data/advanced_search_terms.csv", row.names = TRUE)
#save(advanced_search_terms, file = "data/advanced_search_terms.RData")

